# Generated by Django 5.0.6 on 2024-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/%Y/%m/%d"),
        ),
    ]
