# Generated by Django 5.0.6 on 2024-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/post-img/%Y/%m/%d"),
        ),
    ]
