# Generated by Django 5.0.6 on 2024-07-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.category"),
            preserve_default=False,
        ),
    ]
